version: "3.9"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"
    networks:
      - app
    volumes:
      - db:/var/lib/postgresql/data
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "${CACHE_REDIS_PORT}:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${CACHE_REDIS_PASSWORD}
    networks:
      - app
    volumes:
      - cache:/data

networks:
  app:

volumes:
  db:
  cache:
