version: "3.9"

services:
  backend:
    build:
      context: ./app/backend
      target: "${NODE_ENV}"
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
      - "${MICROSERVICES_USERS_PORT}:${MICROSERVICES_USERS_PORT}"
    entrypoint: ["npm", "run", "docker:${NODE_ENV}"]
    env_file:
      - .env
    volumes:
      - ./app/backend:/usr/src/backend
    networks:
      - app
  client:
    build:
      context: ./client
      target: "${NODE_ENV}"
    restart: on-failure
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
      - "24678:24678"
    command: npm run docker:${NODE_ENV}
    env_file: .env
    environment:
      PORT: ${CLIENT_PORT}
    volumes:
      - ./client:/usr/src/client
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"
    networks:
      - app
    volumes:
      - db:/var/lib/postgresql/data
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "${CACHE_REDIS_PORT}:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${CACHE_REDIS_PASSWORD}
    networks:
      - app
    volumes:
      - cache:/data
  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - app

networks:
  app:

volumes:
  db:
  cache:
